#端口配置和访问路径配置
server:
  port: 8090
  servlet:
    context-path: /chapter1
#切换配置文件
spring:
  profiles:
    active: dev
#gril:
#  age: 10
#  name: fuzhongyu
#打包后切换配置文件等相关属性：
#1.mvn package
#2.进入target目录下执行java -jar chapter2-0.0.1-SNAPSHOT.jar --spring.profiles.active=test --my1.age=32
#3.输入测试地址
