spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#com.mysql.jdbc.Driver 是 mysql-connector-java 5中的，
#com.mysql.cj.jdbc.Driver 是 mysql-connector-java 6中的
#mybatis.mapper-locations=classpath:com/battcn/mapper/*.xml
#mybatis.configuration.map-underscore-to-camel-case:省略部分映射配置
#springboot打包配置
#<resources>
#    <resource>
#        <directory>src/main/resources</directory>
#    </resource>
#    <resource>
#        <directory>src/main/java</directory>
#        <includes>
#            <include>**/*.xml</include>
#        </includes>
#        <filtering>true</filtering>
#    </resource>
#</resources>