#默认日志级别 INFO、WARN、ERROR
spring:
  output:
    ansi:
      enabled: never
  profiles:
    active: dev
debug: true
logging:
  file:
    max-size: 10MB
    max-history: 0
  path: E:/springboot.log
#  config: classpath:logging-config.xml
